run-name: Deploy app

on:
  push:
    branches: [main]
    paths:
      - 'frontends/apps/app/**'
      - 'frontends/core/**'
      - 'frontends/packages/**'
      - 'shared/**'

  # Allow manual trigger
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Build
        run: yarn turbo build --filter=app
        shell: bash

      - name: Upload source maps to PostHog
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/PostHog/posthog/releases/download/posthog-cli-v0.0.5/posthog-cli-installer.sh | sh
          /github/home/.posthog/posthog-cli-update
          /github/home/.posthog/posthog-cli --host https://eu.posthog.com sourcemap inject --directory ./frontends/apps/app/dist
        env:
          POSTHOG_CLI_ENV_ID: ${{ secrets.POSTHOG_CLI_ENV_ID }}
          POSTHOG_CLI_TOKEN: ${{ secrets.POSTHOG_CLI_TOKEN }}

      - name: Delete source maps before deployment
        run: |
          find ./frontends/apps/app/dist -name "*.map" -type f -delete
        shell: bash

      - name: Deploy to Cloudflare
        run: yarn workspace app deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        shell: bash
